-- AlterTable: LoadRequest - Add contractedFleetId (TIER 1.1: Mid-Load Quit Prevention)
-- This field snapshots the driver's fleetId at assignment to prevent payee reversion
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_LoadRequest" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "publicTrackingCode" TEXT NOT NULL,
    "shipperId" TEXT NOT NULL,
    "pickupFacilityId" TEXT NOT NULL,
    "dropoffFacilityId" TEXT NOT NULL,
    "serviceType" TEXT NOT NULL,
    "commodityDescription" TEXT NOT NULL,
    "specimenCategory" TEXT,
    "temperatureRequirement" TEXT NOT NULL,
    "estimatedContainers" INTEGER,
    "estimatedWeightKg" REAL,
    "declaredValue" REAL,
    "readyTime" DATETIME,
    "deliveryDeadline" DATETIME,
    "isRecurring" BOOLEAN NOT NULL DEFAULT false,
    "directDriveRequired" BOOLEAN NOT NULL DEFAULT false,
    "accessNotes" TEXT,
    "preferredContactMethod" TEXT NOT NULL DEFAULT 'EMAIL',
    "driverInstructions" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "driverId" TEXT,
    "vehicleId" TEXT,
    "assignedAt" DATETIME,
    "acceptedByDriverAt" DATETIME,
    "contractedFleetId" TEXT,
    "gpsTrackingEnabled" BOOLEAN NOT NULL DEFAULT false,
    "gpsTrackingStartedAt" DATETIME,
    "driverDenialReason" TEXT,
    "driverDenialNotes" TEXT,
    "driverDeniedAt" DATETIME,
    "lastDeniedByDriverId" TEXT,
    "chainOfCustodyRequired" BOOLEAN NOT NULL DEFAULT false,
    "signatureRequiredAtPickup" BOOLEAN NOT NULL DEFAULT true,
    "signatureRequiredAtDelivery" BOOLEAN NOT NULL DEFAULT true,
    "electronicPodAcceptable" BOOLEAN NOT NULL DEFAULT true,
    "temperatureLoggingRequired" BOOLEAN NOT NULL DEFAULT false,
    "pickupSignature" TEXT,
    "pickupSignerName" TEXT,
    "pickupSignatureDriverId" TEXT,
    "deliverySignature" TEXT,
    "deliverySignerName" TEXT,
    "deliverySignatureDriverId" TEXT,
    "pickupAttested" BOOLEAN NOT NULL DEFAULT false,
    "pickupAttestedAt" DATETIME,
    "deliveryAttested" BOOLEAN NOT NULL DEFAULT false,
    "deliveryAttestedAt" DATETIME,
    "signatureUnavailableReason" TEXT,
    "signatureFallbackPhoto" TEXT,
    "pickupTemperature" REAL,
    "pickupTempRecordedAt" DATETIME,
    "deliveryTemperature" REAL,
    "deliveryTempRecordedAt" DATETIME,
    "temperatureMin" REAL,
    "temperatureMax" REAL,
    "pickupTempException" BOOLEAN NOT NULL DEFAULT false,
    "deliveryTempException" BOOLEAN NOT NULL DEFAULT false,
    "temperatureExceptionNotes" TEXT,
    "actualPickupTime" DATETIME,
    "actualDeliveryTime" DATETIME,
    "lateDeliveryFlag" BOOLEAN NOT NULL DEFAULT false,
    "lateDeliveryReasonNotes" TEXT,
    "quoteAmount" REAL,
    "quoteCurrency" TEXT NOT NULL DEFAULT 'USD',
    "quoteNotes" TEXT,
    "quoteExpiresAt" DATETIME,
    "quoteAcceptedAt" DATETIME,
    "driverQuoteAmount" REAL,
    "driverQuoteNotes" TEXT,
    "driverQuoteSubmittedAt" DATETIME,
    "driverQuoteExpiresAt" DATETIME,
    "shipperQuoteDecision" TEXT,
    "shipperQuoteDecisionAt" DATETIME,
    "invoiceId" TEXT,
    "invoicedAt" DATETIME,
    "shipperPaymentStatus" TEXT,
    "shipperPaidAt" DATETIME,
    "shipperPaymentMethod" TEXT,
    "createdByDriverId" TEXT,
    "cancellationReason" TEXT,
    "cancelledBy" TEXT,
    "cancelledById" TEXT,
    "cancelledAt" DATETIME,
    "cancellationBillingRule" TEXT,
    "rawEmailContent" TEXT,
    "emailSubject" TEXT,
    "emailFrom" TEXT,
    "autoCalculatedDistance" REAL,
    "autoCalculatedTime" INTEGER,
    "suggestedRateMin" REAL,
    "suggestedRateMax" REAL,
    "deadheadStartingLocation" TEXT,
    "deadheadDistance" REAL,
    "totalDistance" REAL,
    "ratePerMile" REAL,
    "createdVia" TEXT NOT NULL DEFAULT 'WEB_FORM',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LoadRequest_shipperId_fkey" FOREIGN KEY ("shipperId") REFERENCES "Shipper" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "LoadRequest_pickupFacilityId_fkey" FOREIGN KEY ("pickupFacilityId") REFERENCES "Facility" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "LoadRequest_dropoffFacilityId_fkey" FOREIGN KEY ("dropoffFacilityId") REFERENCES "Facility" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "LoadRequest_driverId_fkey" FOREIGN KEY ("driverId") REFERENCES "Driver" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "LoadRequest_createdByDriverId_fkey" FOREIGN KEY ("createdByDriverId") REFERENCES "Driver" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "LoadRequest_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "LoadRequest_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "LoadRequest_contractedFleetId_fkey" FOREIGN KEY ("contractedFleetId") REFERENCES "Fleet" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_LoadRequest" SELECT 
    "id", "publicTrackingCode", "shipperId", "pickupFacilityId", "dropoffFacilityId",
    "serviceType", "commodityDescription", "specimenCategory", "temperatureRequirement",
    "estimatedContainers", "estimatedWeightKg", "declaredValue", "readyTime", "deliveryDeadline",
    "isRecurring", "directDriveRequired", "accessNotes", "preferredContactMethod", "driverInstructions",
    "status", "driverId", "vehicleId", "assignedAt", "acceptedByDriverAt",
    NULL as "contractedFleetId",
    "gpsTrackingEnabled", "gpsTrackingStartedAt", "driverDenialReason", "driverDenialNotes",
    "driverDeniedAt", "lastDeniedByDriverId", "chainOfCustodyRequired", "signatureRequiredAtPickup",
    "signatureRequiredAtDelivery", "electronicPodAcceptable", "temperatureLoggingRequired",
    "pickupSignature", "pickupSignerName", "pickupSignatureDriverId", "deliverySignature",
    "deliverySignerName", "deliverySignatureDriverId", "pickupAttested", "pickupAttestedAt",
    "deliveryAttested", "deliveryAttestedAt", "signatureUnavailableReason", "signatureFallbackPhoto",
    "pickupTemperature", "pickupTempRecordedAt", "deliveryTemperature", "deliveryTempRecordedAt",
    "temperatureMin", "temperatureMax", "pickupTempException", "deliveryTempException",
    "temperatureExceptionNotes", "actualPickupTime", "actualDeliveryTime", "lateDeliveryFlag",
    "lateDeliveryReasonNotes", "quoteAmount", "quoteCurrency", "quoteNotes", "quoteExpiresAt",
    "quoteAcceptedAt", "driverQuoteAmount", "driverQuoteNotes", "driverQuoteSubmittedAt",
    "driverQuoteExpiresAt", "shipperQuoteDecision", "shipperQuoteDecisionAt", "invoiceId",
    "invoicedAt", "shipperPaymentStatus", "shipperPaidAt", "shipperPaymentMethod",
    "createdByDriverId", "cancellationReason", "cancelledBy", "cancelledById", "cancelledAt",
    "cancellationBillingRule", "rawEmailContent", "emailSubject", "emailFrom",
    "autoCalculatedDistance", "autoCalculatedTime", "suggestedRateMin", "suggestedRateMax",
    "deadheadStartingLocation", "deadheadDistance", "totalDistance", "ratePerMile",
    "createdVia", "createdAt", "updatedAt"
FROM "LoadRequest";
DROP TABLE "LoadRequest";
ALTER TABLE "new_LoadRequest" RENAME TO "LoadRequest";
PRAGMA foreign_keys=ON;

-- CreateIndex
CREATE INDEX "LoadRequest_contractedFleetId_idx" ON "LoadRequest"("contractedFleetId");

